### ISSUE TITLE
Headings with automatic numbering

### ISSUE THREAD

**Issue by peng-howard** [rstudio/blogdown#140]
`@likanzhan` closed a similar issue in this [post](https://github.com/rstudio/blogdown/issues/80) which is useless for me.

**Comment by yihui** [comment]
What did you try?

**Comment by peng-howard** [comment]
I have a Rmd file in `\content\` directory and add `number_sections: true` in the YAML metadata like this 

```
---
title: Building A Blog with Blogdown
author: author name
date: '2017-07-05'
output:
  blogdown::html_page:
    toc: true
    number_sections: true
slug: hugo
tags: [Hugo, GitHub]
---

Contents...

# h1 heading

## h2 heading

```

After saving the file, RStudio shows logs as follows:

```txt
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
10 regular pages created
30 other pages created
0 non-page files copied
0 paginator pages created
8 tags created
1 categories created
total in 28 ms
```

Then in the resulting previews webpage at `http://127.0.0.1:4321/2017/02/hugo/`, the headings have not been numered like the format `1 h1 heading`, `1.1 h2 heading` as I have expected,  just shown as `h1 heading`, `h2 heading`, left the section numbers dismissed.

Here is some information may useful about my R settings:

```txt
platform       x86_64-w64-mingw32                      
arch           x86_64                                  
os             mingw32                                 
system         x86_64, mingw32                         
status         beta                                    
major          3                                       
minor          4.1                                     
year           2017                                    
month          06                                      
day            19                                      
svn rev        72811                                   
language       R                                       
version.string R version 3.4.1 beta (2017-06-19 r72811)
nickname       Single Candle 
```
