### ISSUE TITLE
Automatic deployment using Travis CI

### ISSUE THREAD

**Issue by pat-s** [rstudio/blogdown#26]
@yihui Referring to your comment: http://disq.us/p/1eyc771

Is there already a setup for Travis CI to use automatic deployment? Your `travis.yml` does not seem to do deployment right now? 
ATM I´m using `wercker` as this is suggested by Hugo. While this works using a "two repo" solution with Github pages, the deploy script does not support .Rmd files but only .md files. 

`Wercker.yml` 

```yml
box: golang:latest

build:
  steps:
    - script:
        name: initialize and update git submodules
        code: |
            git submodule init
            git submodule update --remote --recursive
    - arjen/hugo-build:
        version: "HEAD"
        theme: academic

deploy:
  steps:
    - install-packages:
            packages: git
    - leipert/git-push:
            gh_oauth: $GIT_TOKEN
            repo: pat-s/pat-s.github.io
            branch: master
            basedir: public
```
