### ISSUE TITLE
kable table not rendering

### ISSUE THREAD

**Issue by nllspc** [rstudio/blogdown#280]
My [table](https://erbo.rbind.io/blog/2018-03-09-a-baseball-dashboard-in-time-for-baseball-season/) (bottom of post in the link) is rendering as a standard markdown table after saving and `serve_site` 
even though I'm using `knitr::kable`. When I knit it in a different RMarkdown file, it renders properly. Here's the code chunk.

````
```{r eda-tab, echo=FALSE}

knitr::kable(matrix(c(
      '7 yrs', '67%',
      '6 yrs', '78%',
      '5 yrs', '86%',
      '4 yrs', '92%',
      NULL
), ncol = 2, byrow=TRUE, dimnames = list(NULL, c('Cutoff', '% Remaining'))),
booktabs=TRUE, caption = 'Inductees')

````

I've tried using a `tribble`, `data.frame` instead but I'm still getting the same results. I've also tried using `kableExtra` . Thought it might be my YAML output but I removed it and it didn't help. 

````
---
title: A Baseball Dashboard in Time for Baseball Season
author: Eric Book
date: '2018-03-09'
slug: a-baseball-dashboard-in-time-for-baseball-season
categories:
  - shiny
  - sports-analysis
  - scraping
  - eda
tags:
  - shiny
  - outliers
  - rvest
  - ggridges
  - DT
draft: FALSE
output:
      blogdown::html_page:
            toc: true
            toc_depth: 2
---
````

Can't find anyone on SO or in your issues that's encountered this problem. It makes me think it might be a [theme](https://github.com/parsiya/Hugo-Octopress) issue but I don't think the creator is a R user so I'm not sure how to address it with them. Here's my `sessionInfo("blogdown")`.

````
> sessionInfo("blogdown")
R version 3.4.3 (2017-11-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
character(0)

other attached packages:
[1] blogdown_0.5.10

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     bookdown_0.7     grDevices_3.4.3  withr_2.1.1.9000 digest_0.6.15    rprojroot_1.3-2 
 [7] backports_1.1.2  magrittr_1.5     evaluate_0.10.1  datasets_3.4.3   stringi_1.1.6    utils_3.4.3     
[13] graphics_3.4.3   rmarkdown_1.9    devtools_1.13.4  base_3.4.3       tools_3.4.3      stringr_1.3.0   
[19] xfun_0.1         yaml_2.1.18      compiler_3.4.3   stats_3.4.3      memoise_1.1.0    htmltools_0.3.6 
[25] knitr_1.20       methods_3.4.3   
````

**Comment by gadenbuie** [comment]
Unless I'm missing something, everything is working fine on the `knitr::kable` and `blogdown` side. `knitr::kable()` is giving you a standard HTML table, which is great, that's what that function is good at.

The reason it doesn't look right is because there's no fancy CSS styling on the table elements. From what I can tell, you're using the [hugo-octopress theme](https://github.com/parsiya/Hugo-Octopress) and it appears that there is very minimal CSS styling for the table elements. 

[Here is the relevant CSS](https://github.com/parsiya/Hugo-Octopress/blob/a8d0587810a6459fc07d01e947ad50cabfab142d/static/css/hugo-octopress.css#L2143-L2153) that is being applied to your tables:

```css
table,
th,
td
 {
    border: 1px solid black;
    padding: 3px;
}
th {
    font-weight: bold;
    text-align: center;
}
```

which should give a table that looks like the one you're seeing.

What you can do to fix this is create a custom `.css` file for the table stylings (or Google around for one) inside the folder `static/css`, say `static/css/tables.css`. Then change the line for CSS overides in your [config.toml](https://github.com/nllspc/erbo_rbind/blob/5d87fb08253340995d91b90f65e3f11d006476dd/config.toml#L92) to point to `customCSS = ["css/tables.css"]`. For reference, you can also take a look at the [hugo-octopress documentation on custom CSS](https://github.com/parsiya/Hugo-Octopress#cssoverride), which you may find helpful.
