### ISSUE TITLE
Call build_site() but only render 'new' pages like what happens with serve_site()

### ISSUE THREAD

**Issue by jimmyday12** [rstudio/blogdown#468]
---

Hi - I'm asking a question rather than an issue here. I'm trying to call `build_site()` but only render pages where the `.Rmd` file is newer than the `.html` file, similar to what happens in `serve_site()`. 

This relates to using github actions to periodically update a specific page on my site and rebuild it before publishing to Netlify. The specific reason for this is that I have one page that I want to update every day as it pulls in new data and updates a table and chart. 

This is entirely possible to do locally by simply having a script that does something like the following and manually running it each day.

```
library(blogdown)
blogdown:::touch_file('path_to_page.Rmd')
blogdown::serve_site()
```

If I run this locally and commit the changes, then Netlify will rebuild the site and everything will be updated. What I'm trying to do is replicate the above workflow using github actions so that I don't have to do it manually. 

I can get pretty close but I think running `blogdown::serve_site()` doesn't work within the github actions workflow. I asked this question (in a bit more of a convoluted way) on [Stack Overflow](https://stackoverflow.com/questions/62825976/using-blogdown-with-github-actions-alternative-to-serve-site) but haven't received a response. 

For my github actions setup, I can use the following

```
name: Get new data and rebuild site

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches:
      - master

jobs:
  scrape-and-commit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages("blogdown")'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.66.0")'
      - name: Touch files
        run: Rscript -e 'blogdown:::touch_file("path_to_file.Rmd)' 
      - name: Build site
        run: Rscript -e 'blogdown::serve_site()'
```

(note - I haven't shown the github commit part of the workflow). 

This seems to just cancel itself after a while, I suspect because `serve_site()` is meant to be run locally to render a preview which probably doesn't work on the virtual machine. 

```
Serving the directory /Users/runner/work/plussixoneblog/plussixoneblog at http://127.0.0.1:4321
##[error]The operation was canceled.
```

I could in theory run `blogdown::build_site()` here instead but my big problem is that I don't want every post or page re-rendered. I just want to render the file that I _touched_. The reason being that the older posts/pages reference data that has since changed and I don't want them updated. 

So basically - I'm wondering if there is a way to replicate the `serve_site` ability to just render files where the `.Rmd` file is newer than the `.html` file without rendering the site locally? Or - has anyone else had any luck using github actions/netlify to rebuild just parts of a site rather than the whole thing?

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('blogdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/blogdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

**Comment by jimmyday12** [comment]
Hi @yihui - just checking to see if there was any advice here? Or it's just not possible what I'm trying to do?

**Comment by jimmyday12** [comment]
Hi all - I managed to work this one out. Two things I did seemed to help here. 

First - using `blogdown::build_site(local = TRUE)`. The `local` part was what I had been missing earlier. 

I also needed to add the `touch_file` part of the action to the run command. I'm not sure if that was actually important but it was the step that finally got this whole process working for me so I'm going to say yes. 

The extract is below. In the 'Install Packages' section you also need to add packages that are used in the files you touch. 

```
jobs:
  touch-and-rebuild:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("here", "blogdown"))'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.66.0")'
      - name: Build site
        run: |
          blogdown:::touch_file(here::here("path", "to", "file.Rmd"))
          blogdown:::build_site(TRUE)
        shell: Rscript {0} 
```

After this, you'll need some code to commit
