### ISSUE TITLE
New post add-in strips helpful comments from YAML

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#560]
In the academic theme, the archetype files are helpfully commented like:

https://github.com/rbind/apreshill/blob/master/archetypes/post/index.md

```
---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "{{ replace .Name "-" " " | title }}"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: {{ .Date }}
lastmod: {{ .Date }}
featured: false
draft: false
disable_jquery: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---
```

But when I use the new-post addin I see:

```
---
title: Test
author: Alison Hill
date: '2021-01-05'
slug: []
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-01-05T07:35:43-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```

Can blogdown preserve comments in the YAML here? Oftentimes the comments are the 'documentation' for the theme.
