### ISSUE TITLE
3.4 gitlab pages improvement

### ISSUE THREAD

**Issue by anna-doizy** [rstudio/blogdown#603]
Hi Yihui, Amber & Alison,

I'm not completely sure of myself, but as it worked for me maybe it can help other people.
I changed my `gitlab-ci.yml` from
``` yml
image: rocker/tidyverse

before_script:
  - apt-get update
  - R -e "install.packages(c('blogdown', and_so_on), repos='https://cran.rstudio.com/')"
  - R -e "blogdown::install_hugo()"

pages:
  script:
  - R -e "blogdown::build_site()"
  artifacts:
    paths:
    - public
  only:
  - master
  ```
to the usual hugo one
``` yml
image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
```
and the deployment time dropped from 30 minutes to **30 seconds**! Tidyverse and the other packages I needed are the longest to load. The new config seems to work for `.rmd` content as well because of their trailing `.html`, so it is a bit of a hack because this was probably not expected by you, developer ;)

Well I was thinking maybe it is worth a while to test the robustness of this config a bit further (I use wowchemy and icon hugo themes but don't have any sophisticated workflow) and let it know to the wide world.

Cheers
Anna
