### ISSUE TITLE
troubleshooting disqus

### ISSUE THREAD

**Issue by IanniMuliterno** [rstudio/blogdown#635]
Hello, so I am using a recent version of blogdown, the archive is now `config.yaml` instead of `config.toml`. My config looks like this
```
baseURL: "https://iannimuliterno.github.io/blog2021/"
languageCode: en
DefaultContentLanguage: en
title: config yaml draft do meu blog
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
publishDir: "docs/"
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
disqusShortname: annymuliterno

markup:
  goldmark:
    renderer:
      unsafe: true

```
Only adding `disqusShortname: annymuliterno` wasn't enough, so I've also tried 

- 1 creating disqus.html at `themes\anatole\layouts\partials\` 
- 2 running build_site()

and it did not work, so I noticed that inside  `themes\anatole\layouts\partials\`  exists a directory called comments and tried moving `disqus.html` to `themes\anatole\layouts\partials\comments`, then ran build_site() again and still I bump into the trobleshooting issue, I'd love to add comments to my blog so any help will be greatly appreciated.

for the record, my disqus.html looks like this : 

```
<div id="disqus_thread"></div>
<script>
(function() {
var d = document, s = d.createElement('script');
s.src = 'https://annymuliterno.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

```
