### ISSUE TITLE
Interactive plot and html table is not being rendered

### ISSUE THREAD

**Issue by diwashrestha** [rstudio/blogdown#715]
**Theme:** wowchemy/starter-hugo-academic

**Issue:** Interactive plot made with plotly and tables made with DT::datatable and rmarkdown::paged_table is not being rendered in the website while both are rendering in rmarkdown. Please review the attached picture.

**Attachment:**
 **_Plotly_**
![image](https://user-images.githubusercontent.com/19636247/178240392-1edf7a1f-d9e0-4d3d-96ac-f123724a448f.png)

**_rmarkdown table_**
![image](https://user-images.githubusercontent.com/19636247/178240668-db5a0ec0-6f41-4f10-b54f-5ab30e55c8dc.png)

**_config.yaml_**
```yaml
theme: starter-academic
title: Diwashrestha
baseurl: https://diwashrestha.com.np/
copyright: '© Diwash Shrestha 2022'
enableGitInfo: no
defaultContentLanguage: en
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
summaryLength: 30
paginate: 10
enableEmoji: yes
enableRobotsTXT: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmarkdown$
  - _files$
  - _cache$
permalinks:
  authors: /author/:slug/
  categories: /category/:slug/
  publication_types: /publication-type/:slug/
  tags: /tag/:slug/
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes: webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: no
  tableOfContents:
    endLevel: 3
    startLevel: 2
imaging:
  anchor: smart
  quality: 90
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: tags
      weight: 80
    - name: categories
      weight: 70
    - name: authors
      weight: 20
  threshold: 80
  toLower: yes
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
```

```R
xfun::session_info('blogdown')
```
```
R version 4.1.3 (2022-03-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora Linux 36 (Workstation Edition), RStudio 2022.2.3.492

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
  LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3  blogdown_1.10    bookdown_0.27    bslib_0.3.1      digest_0.6.29   
  evaluate_0.15    fastmap_1.1.0    fs_1.5.2         glue_1.6.2       graphics_4.1.3  
  grDevices_4.1.3  highr_0.9        htmltools_0.5.2  httpuv_1.6.5     jquerylib_0.1.4 
  jsonlite_1.8.0   knitr_1.39       later_1.3.0      magrittr_2.0.3   methods_4.1.3   
  mime_0.12        promises_1.2.0.1 R6_2.5.1         rappdirs_0.3.3   Rcpp_1.0.8.3    
  rlang_1.0.2      rmarkdown_2.14   sass_0.4.1       servr_0.24       stats_4.1.3     
  stringi_1.7.6    stringr_1.4.0    tinytex_0.39     tools_4.1.3      utils_4.1.3     
  xfun_0.31        yaml_2.3.5      

Hugo version: 0.78.2
