### ISSUE TITLE
Unable to serve site after updates

### ISSUE THREAD

**Issue by dayabin** [rstudio/blogdown#744]
Howdy,

Thanks for clicking in. I made my website with blogdown and hugo. After a regular check of the release note in wowchemy, I updated the go.mod file and the config.yaml file (with the latest `module`). However, the site won't serve after the updates.

Please see my `go.mod` and `config.yaml` below. The complete package of files can be found in [github](https://github.com/dayabin/PersonalWebisteNewVersion)

```
module github.com/wowchemy/starter-hugo-academic

go 1.15

require (
  github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
  github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
  github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5
)
```

```
module:
imports:
       - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
      - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
      - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5
```

After I clicked the "Serve Site" button in RStudio, I got error messages saying

```
Launching the server via the command:
  hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -D -F --navigateToChanged
Error: go: errors parsing go.mod:
C:\work\PersonalWebsite\mywebsite\go.mod:6:3: usage: require module/path v1.2.3
C:\work\PersonalWebsite\mywebsite\go.mod:7:3: usage: require module/path v1.2.3
C:\work\PersonalWebsite\mywebsite\go.mod:8:3: usage: require module/path v1.2.3
Error: failed to download modules: failed to execute 'go [mod download]': failed to execute binary "go" with args [mod download]: go: errors parsing go.mod:
C:\work\PersonalWebsite\mywebsite\go.mod:6:3: usage: require module/path v1.2.3
C:\work\PersonalWebsite\mywebsite\go.mod:7:3: usage: require module/path v1.2.3
C:\work\PersonalWebsite\mywebsite\go.mod:8:3: usage: require module/path v1.2.3
 *errors.errorString
```

Any ideas??? Thank you for the help.
