### ISSUE TITLE
Numbered sections in blogdown?

### ISSUE THREAD

**Issue by likanzhan** [rstudio/blogdown#80]
I added the following arguments to the front matter of my blogdown post, intending to number the sections of my rmd file. But it doesn't work. Any suggestions?

```
output:
  blogdown::html_page:
    number_sections: true
    toc: true
```

**Comment by yihui** [comment]
Did you solve your problem?

**Comment by likanzhan** [comment]
Sorry for the bothering. I don't know what happened,  but it works now.  Actually, I have a minor problem relating to this. The numbered section now is in the format "1 Section Title". I'm wondering whether it is possible to add a dot or something between the number and the section title, such as "1. Section title"?

**Comment by yihui** [comment]
That is a good question. You may use CSS, e.g.

```css
span.header-section-number:after {
    content: ".";
}
```
